// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhlsLygpGhsOJDN3TyyCu46FUGKqasF8',
    appId: '1:296294164908:web:b97499de8f711892dcf209',
    messagingSenderId: '296294164908',
    projectId: 'anireel-app',
    authDomain: 'anireel-app.firebaseapp.com',
    storageBucket: 'anireel-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMzeasaicU3IcRE_kedK2erZPdsGfzCcI',
    appId: '1:296294164908:android:efa13b8bec9746c4dcf209',
    messagingSenderId: '296294164908',
    projectId: 'anireel-app',
    storageBucket: 'anireel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2W2NA_lL_ui7H1fq2ifPZ3SyOH28zxg',
    appId: '1:296294164908:ios:097e99c46474a0cddcf209',
    messagingSenderId: '296294164908',
    projectId: 'anireel-app',
    storageBucket: 'anireel-app.appspot.com',
    iosClientId: '296294164908-03pfc1k6855hgresa7emdq4iv32vka2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS2W2NA_lL_ui7H1fq2ifPZ3SyOH28zxg',
    appId: '1:296294164908:ios:097e99c46474a0cddcf209',
    messagingSenderId: '296294164908',
    projectId: 'anireel-app',
    storageBucket: 'anireel-app.appspot.com',
    iosClientId: '296294164908-03pfc1k6855hgresa7emdq4iv32vka2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );
}
